{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 5\n +  where 5 = <bound method Random.choice of <random.Random object at 0x000002A3171A0CE0>>([1, 2, 3, 4, 5, 6])\n +    where <bound method Random.choice of <random.Random object at 0x000002A3171A0CE0>> = random.choice", "trace": "def test_1():\n>       assert 1 == random.choice(numbers)\nE       assert 1 == 5\nE        +  where 5 = <bound method Random.choice of <random.Random object at 0x000002A3171A0CE0>>([1, 2, 3, 4, 5, 6])\nE        +    where <bound method Random.choice of <random.Random object at 0x000002A3171A0CE0>> = random.choice\n\ntests\\test_rerun.py:9: AssertionError"}, "start": 1666205321397, "stop": 1666205321397, "uuid": "848f2b8a-7164-4296-ac77-e204034d5e8c", "historyId": "e5679bef5fe250984e6aa6c38fd177da", "testCaseId": "3d48bd9a6ac95adfb209debb7a5e14c1", "fullName": "tests.test_rerun#test_1", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_rerun"}, {"name": "host", "value": "NB-100211"}, {"name": "thread", "value": "12156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_rerun"}]}